# Generated by Django 2.2.7 on 2019-11-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='check_in',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='check_out',
            field=models.CharField(max_length=255),
        ),
    ]
